version: '3'

services:
  # nginx:
  #   image: nginx
  #   ports:
  #     - "8080:80"
  #   command: [nginx, '-g', 'daemon off;']
  db:
    image: db
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  web:
    image: python
    entrypoint: /entrypoint.sh
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: mail_drive
      DB_USER: leshka
      DB_PASSWORD: leshka

      MINIO_HOST: minio1
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: set-value-here
      MINIO_SECRET_KEY: set-value-here
    depends_on:
      - db

  minio1:
    image: minio/minio
    volumes:
      - minio-volume1:/export
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: set-value-here
      MINIO_SECRET_KEY: set-value-here
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  minio2:
    image: minio/minio
    volumes:
      - minio-volume2:/export
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: set-value-here
      MINIO_SECRET_KEY: set-value-here
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  minio3:
    image: minio/minio
    volumes:
      - minio-volume3:/export
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: set-value-here
      MINIO_SECRET_KEY: set-value-here
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  minio4:
    image: minio/minio
    volumes:
      - minio-volume4:/export
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: set-value-here
      MINIO_SECRET_KEY: set-value-here
    command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export


## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio-volume1:
  minio-volume2:
  minio-volume3:
  minio-volume4:
  postgres-volume:

